from __future__ import annotations

from datetime import date
from typing import List

from pydantic import BaseModel, Field


class PromotionPlan(BaseModel):
    promo_event_id: str = Field(description="Candidate ID from the analyzer output")
    market: str
    retailer: str
    segment: str
    category: str
    brand: str
    flavor: str
    pack_size: str
    product_group_name: str
    sku_id: str
    sku_description: str
    promo_start_date: date
    promo_end_date: date
    promo_duration: int = Field(description="Duration in days", ge=1)
    offer_type: str = Field(description="Type of promotional offer e.g., percent off, BOGO")
    discount_depth: float = Field(description="Fraction e.g., 0.25 for 25%", ge=0.0, le=1.0)
    unit_price: float = Field(description="Regular unit price before discount from `KPI forecasts` section")
    promo_unit_price: float = Field(description="Unit price during the promotion")
    cogs_per_unit: float = Field(description="Cost of goods sold per unit from `KPI forecasts` section")
    gross_margin_pct: float = Field(description="Gross margin percentage from `KPI forecasts` section")
    baseline_volume: float = Field(description="Baseline volume without promotion from `KPI forecasts` section")
    incremental_volume: float = Field(description="Incremental volume due to promotion from `KPI forecasts` section")
    promo_investment: float = Field(description="Total investment by the company in the promotion from `KPI forecasts` section")
    profit_system: float = Field(description="Incremental profit generated by the promotion from `KPI forecasts` section")
    incremental_profit_system: float = Field(description="Incremental profit over baseline from `KPI forecasts` section")
    profit_roi: float = Field(description="profit_roi from `KPI forecasts` section")


class PortfolioOutput(BaseModel):
    promotions: List[PromotionPlan]


__all__ = [
    "PromotionPlan",
    "PortfolioOutput",
]
